config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, path: 'employee'
  root to: 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => e
        raise e if get?

        if has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class='navbar is-fixed-top is-primary is-light has-shadow'>
    <div class='navbar-brand'>
      <%= link_to 'Company', root_path, class: 'navbar-item' %>
    </div>
    <div class='navbar-menu'>
      <div class='navbar-start'>
        <p class="buttons">
          <a class="button is-primary is-small" href='https://github.com/Gludek/employee-platform-Rails7' >
              <span class="icon">
                <i class="fab fa-github"></i>
              </span>
            <span>GitHub</span>
          </a>
      </div>
      <div class='navbar-end'>
        <% if employee_signed_in? %>
<!--              <span class='navbar-item info has-background-primary-dark has-text-centered my-0 py-0 is-flex is-align-content-space-evenly'>-->
<!--                <div class=' kudo-container is-flex is-flex-direction-row is-justify-content-space-around is-align-items-center'>-->
<!--                  <p>Current points<br>-->
                    <%#= current_employee.points %>
<!--                  </p>-->
                  <%#= inline_svg_tag('kudo.svg', class: 'kudo') %>
<!--                </div>-->
<!--                <div>-->
<!--                  Avaible Kudos<br>-->
                  <%#= current_employee.number_of_available_kudos  %>
<!--                </div>-->
<!--              </span>-->
<!--          <div class="navbar-item has-dropdown is-hoverable">-->
            <%#= link_to "Pages", root_path, class: "navbar-link"%>
<!--            <div class="navbar-dropdown">-->
              <%#= link_to "Kudos", kudos_path, class: "navbar-item"%>
              <%#= link_to "Rewards", rewards_path, class: "navbar-item"%>
              <%#= link_to "Orders", orders_employee_path(current_employee.id), class: "navbar-item"%>
              <%#= link_to "My Profile", employee_path(current_employee), class: "navbar-item"%>
<!--            </div>-->
<!--          </div>-->
          <%= link_to 'Sign out', destroy_employee_session_path, data: {turbo_method: :delete}, class:'is-link navbar-item' %>
        <% else %>
          <%= link_to 'Sign in', new_employee_session_path, class:'navbar-item' %>
          <%= link_to 'Sign up', new_employee_registration_path, class:'navbar-item' %>
        <% end %>
      </div>
    </div>
  </nav>
  <% if notice %>
    <p class=" notification notice"><%= notice %></p>
  <% elsif alert%>
    <p class="notification alert is-warning"><%= alert %></p>
  <% end %>
  <section class="section">
    <div class="content">
      <div class="container is-max-desktop">
        <div class='box'>
          <%= yield %>
        </div>
      </div>
    </div>
  </section>
  </body>
</html>